# Generated by Django 5.1.15 on 2026-07-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date'], 'verbose_name': 'پیغام', 'verbose_name_plural': 'پیغام ها'},
        ),
    ]
