# Generated by Django 5.1.15 on 2026-07-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'کتگوری', 'verbose_name_plural': 'کتگوری ها'},
        ),
    ]
